# Generated by Django 4.2.16 on 2026-08-17 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resumetemplate',
            options={'ordering': ['sort_order', 'name']},
        ),
        migrations.AddField(
            model_name='resume',
            name='achievements',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='career_objective',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='resume',
            name='internships',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='publications',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='resume_customization',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='resume',
            name='template_style',
            field=models.CharField(default='classic', max_length=50),
        ),
        migrations.AddField(
            model_name='resume',
            name='volunteer_experience',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='resume',
            name='website_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='best_for',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='category',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='sort_order',
            field=models.IntegerField(default=0),
        ),
    ]
