# Generated by Django 6.1 on 2026-08-19 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_alter_resumetemplate_options_resume_achievements_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='resumetemplate',
            name='pdf_config',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='section_order_experienced',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='section_order_fresher',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='resumetemplate',
            name='styles',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
